development:
  app_id: ENV['fb_app_id'] 
  secret_key: ENV['fb_app_secret']  
  callback_url: http://localhost:3000/
 
production:
  app_id: ENV['fb_app_id'] 
  secret_key: ENV['fb_app_secret'] 
  callback_url: http://gunslingr.heroku.com
  
